input {
  tcp {
    port => 5044
    codec => line
  }
}

filter {
  grok {
    match => { "message" => 
    "HTTP %{WORD:requestMethod} %{URIPATHPARAM:requestPath} responded %{NUMBER:statusCode} in %{NUMBER:elapsed} ms"
     }
  }
  if [requestPath] == "/metrics" {
    drop { }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "nestrukturirano-%{+YYYY.MM.dd}"
  }
}
